### ISSUE TITLE
Incompatibility with EMI: bars don't show when enabling EMI's "Move Effects" option

### ISSUE THREAD

**Issue by xR4YM0ND** [A5b84/status-effect-bars#4] opened 2022-10-28 14:59 UTC
[Latest.Log](https://gist.github.com/SpigotDE/9e1f9a910b078539ac6b89d90861a841)

The config is not working, even after restarting the client:

![Screenshot 2022-10-28 165647](https://user-images.githubusercontent.com/97298005/198662965-b8ec0d06-b9ba-4164-9b69-9c38de10475e.png)
![2022-10-28_16 55 35](https://user-images.githubusercontent.com/97298005/198663064-366985b3-459f-4838-9927-6ad101418b08.png)
![2022-10-28_16 55 50](https://user-images.githubusercontent.com/97298005/198663110-f4d2d6d3-67bf-4103-8e6b-94d2b38baf9e.png)

**Comment by SpigotDE** [comment] 2022-10-28 14:59
I wanna disable the icons over the inventory , but i wanna keep the icons in the upper right corner

**Comment by A5b84** [comment] 2022-11-02 17:29
The bars not displaying is caused by EMI, setting "Move Effects" to false (under "UI" in EMI's config) makes them reappear (relevant mixin in EMI: [here](https://github.com/emilyploszaj/emi/blob/1e11ce95143b4cb979342a955c488f743387b886/src/main/java/dev/emi/emi/mixin/AbstractInventoryScreenMixin.java#L40))

If you want to completely hide potion effects in your inventory, I don't think either mod can do that

**Comment by SpigotDE** [comment] 2022-11-02 20:34
Ok but more important, you see the effects in the inventory overlapped with tge tabs

Can i move the status effects a bit higher, so that i can cycle through the tabs again?

**Comment by A5b84** [comment] 2022-11-02 21:03
Isn't that an issue with EMI and/or whatever mod added those tabs? Because in that case I can't really do anything

**Comment by SpigotDE** [comment] 2022-11-02 22:05
The mod is LevelZ & JobsAddition

Could you make a config for a Y axis so we could move the status bars up by some pixels 

Or make a compat ?

**Comment by A5b84** [comment] 2022-11-02 22:19
If this is an incompatibility between EMI and LevelZ/JobsAddition, I don't think I should be the one fixing it (or at least not in this mod)

**Comment by SpigotDE** [comment] 2022-11-03 01:11
No, i mean the Status Effect Bar , forget EMI

**Comment by A5b84** [comment] 2022-11-03 10:59
If you mean adding an option to move potion effects vertically in the inventory, in my opinion that's out of scope for this mod

(Since EMI is the one moving the potion effects, I think it would be better for this option to be in EMI)

**Comment by SpigotDE** [comment] 2022-11-03 20:33
Oh i see yeah , sry my brain checked out.

**Comment by A5b84** [comment] 2022-11-03 20:39
All good, I'll just keep the issue open for the incompatibility with EMI

**Comment by A5b84** [comment] 2023-06-13 20:31
Couldn't reproduce the issue with version 1.0.2 of EMI in 1.20.1 so I'll assume it's been fixed

**Closed by A5b84** 2023-06-13 20:31 UTC
Labels: bug
